module.exports = {
  projects: [
    '<rootDir>/apps/ngshop',
    '<rootDir>/apps/admin',
    '<rootDir>/libs/products',
    '<rootDir>/libs/users',
    '<rootDir>/libs/orders',
    '<rootDir>/libs/ui',
    '<rootDir>/apps/ngshop-api-node',
    '<rootDir>/apps/ngshop-api-express',
    '<rootDir>/apps/ngshop-api-nest',
    '<rootDir>/libs/api/nest/shared/port',
    '<rootDir>/libs/api/nest/shared/infrastructure',
    '<rootDir>/libs/api/nest/shared/users/core/domain',
    '<rootDir>/libs/api/nest/shared/common',
    '<rootDir>/libs/api/nest/shared/user/core/application-services',
    '<rootDir>/libs/api/nest/shared/user/core/domain-services',
    '<rootDir>/libs/api/nest/shared/user/core/domain',
    '<rootDir>/libs/api/nest/shared/user/infrastructure',
    '<rootDir>/libs/api/nest/shared/user/shell',
    '<rootDir>/libs/api/nest/shared/user/ui-rest',
  ],
};
